# Generated by Django 4.0.3 on 2022-03-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_candidate_vacancy_candidateprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='candidates_apply',
            field=models.TextField(blank=True),
        ),
    ]
